package dev.chinh.portfolio.auth;

import dev.chinh.portfolio.auth.dto.AuthResponse;
import dev.chinh.portfolio.auth.dto.LoginRequest;
import dev.chinh.portfolio.auth.dto.RefreshRequest;
import dev.chinh.portfolio.auth.dto.RegisterRequest;
import dev.chinh.portfolio.auth.jwt.JwtAuthenticationFilter;
import dev.chinh.portfolio.auth.jwt.JwtService;
import dev.chinh.portfolio.auth.session.Session;
import dev.chinh.portfolio.auth.session.SessionService;
import dev.chinh.portfolio.auth.user.User;
import dev.chinh.portfolio.auth.user.UserDto;
import dev.chinh.portfolio.auth.user.UserService;
import dev.chinh.portfolio.shared.error.ErrorDetail;
import dev.chinh.portfolio.shared.error.ErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;
import java.util.UUID;

/**
 * Controller for authentication endpoints.
 */
@RestController
@RequestMapping("/api/v1/auth")
@Tag(name = "Authentication", description = "Authentication endpoints")
public class AuthController {

    private final UserService userService;
    private final JwtService jwtService;
    private final SessionService sessionService;

    public AuthController(UserService userService, JwtService jwtService, SessionService sessionService) {
        this.userService = userService;
        this.jwtService = jwtService;
        this.sessionService = sessionService;
    }

    /**
     * Register a new user with email and password.
     */
    @Operation(summary = "Register a new user", description = "Register with email and password")
    @ApiResponse(responseCode = "201", description = "User registered successfully")
    @ApiResponse(responseCode = "409", description = "Email already exists")
    @PostMapping("/register")
    public ResponseEntity<?> register(@Valid @RequestBody RegisterRequest request) {
        try {
            User user = userService.register(request);
            UserDto userDto = toUserDto(user);
            return ResponseEntity.status(HttpStatus.CREATED)
                    .body(Map.of("user", userDto));
        } catch (UserService.EmailAlreadyExistsException e) {
            return ResponseEntity.status(HttpStatus.CONFLICT)
                    .body(new ErrorResponse(new ErrorDetail("EMAIL_ALREADY_EXISTS", e.getMessage())));
        }
    }

    /**
     * Login with email and password.
     */
    @Operation(summary = "Login", description = "Login with email and password")
    @ApiResponse(responseCode = "200", description = "Login successful")
    @ApiResponse(responseCode = "401", description = "Invalid credentials")
    @PostMapping("/login")
    public ResponseEntity<?> login(@Valid @RequestBody LoginRequest request) {
        User user = userService.validateCredentials(request)
                .orElseThrow(() -> new InvalidCredentialsException("Invalid email or password"));

        // Generate JWT access token
        String accessToken = jwtService.generateAccessToken(user);

        // Store opaque refresh token in session (generated by SessionService)
        Session session = sessionService.createSession(user);

        AuthResponse response = AuthResponse.of(accessToken, session.getRefreshToken());
        return ResponseEntity.ok(response);
    }

    /**
     * Exception for invalid credentials.
     */
    public static class InvalidCredentialsException extends RuntimeException {
        public InvalidCredentialsException(String message) {
            super(message);
        }
    }

    /**
     * Exception for invalid refresh token.
     */
    public static class InvalidRefreshTokenException extends RuntimeException {
        public InvalidRefreshTokenException(String message) {
            super(message);
        }
    }

    /**
     * Refresh access token using a valid refresh token.
     * Implements token rotation - old token is invalidated and new tokens are issued.
     */
    @Operation(summary = "Refresh access token", description = "Refresh access token with refresh token (token rotation)")
    @ApiResponse(responseCode = "200", description = "Token refreshed successfully")
    @ApiResponse(responseCode = "401", description = "Invalid or expired refresh token")
    @PostMapping("/refresh")
    public ResponseEntity<?> refresh(@Valid @RequestBody RefreshRequest request) {
        // 1. Validate refresh token via SessionService
        Session session = sessionService.validateRefreshToken(request.refreshToken())
                .orElseThrow(() -> new InvalidRefreshTokenException("Invalid or expired refresh token"));

        // 2. Get userId from validated session
        UUID userId = session.getUserId();

        // 3. Delete old session (token rotation)
        sessionService.deleteSession(userId);

        // 4. Load user to generate new access token
        User user = userService.findById(userId)
                .orElseThrow(() -> new InvalidRefreshTokenException("User not found"));

        // 5. Generate NEW access token via JwtService
        String newAccessToken = jwtService.generateAccessToken(user);

        // 6. Create NEW session (new refresh token)
        Session newSession = sessionService.createSession(user);

        AuthResponse response = AuthResponse.of(newAccessToken, newSession.getRefreshToken());
        return ResponseEntity.ok(response);
    }

    /**
     * Logout and invalidate the current session.
     * Requires a valid access token.
     */
    @Operation(summary = "Logout", description = "Logout and invalidate session")
    @ApiResponse(responseCode = "200", description = "Logged out successfully")
    @ApiResponse(responseCode = "401", description = "Authentication required")
    @PostMapping("/logout")
    public ResponseEntity<?> logout(Authentication authentication) {
        // 1. Validate authentication - require valid access token
        if (authentication == null || authentication.getPrincipal() == null) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body(new ErrorResponse(new ErrorDetail("UNAUTHORIZED", "Authentication required")));
        }

        // 3. Get userId from authentication (validated by JwtAuthenticationFilter)
        // The principal is JwtUserPrincipal which stores userId as string
        String userIdStr;
        if (authentication.getPrincipal() instanceof JwtAuthenticationFilter.JwtUserPrincipal principal) {
            userIdStr = principal.getUserId();
        } else {
            userIdStr = authentication.getName();
        }
        UUID userId = UUID.fromString(userIdStr);

        // 4. Delete session via SessionService
        sessionService.deleteSession(userId);

        return ResponseEntity.ok(Map.of("message", "Logged out successfully"));
    }

    private UserDto toUserDto(User user) {
        return new UserDto(
                user.getId(),
                user.getEmail(),
                user.getProvider(),
                user.getRole(),
                user.getCreatedAt()
        );
    }
}
