package dev.chinh.portfolio.auth.oauth2;

import dev.chinh.portfolio.auth.user.AuthProvider;
import dev.chinh.portfolio.auth.user.User;
import dev.chinh.portfolio.auth.user.UserRepository;
import dev.chinh.portfolio.auth.user.UserRole;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService;
import org.springframework.security.oauth2.client.userinfo.OAuth2UserRequest;
import org.springframework.security.oauth2.core.OAuth2AuthenticationException;
import org.springframework.security.oauth2.core.user.DefaultOAuth2User;
import org.springframework.security.oauth2.core.user.OAuth2User;

import java.util.Map;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for GoogleOAuth2UserService.
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("GoogleOAuth2UserService")
class GoogleOAuth2UserServiceTest {

    @Mock
    private UserRepository userRepository;

    private GoogleOAuth2UserService googleOAuth2UserService;

    @BeforeEach
    void setUp() {
        googleOAuth2UserService = new GoogleOAuth2UserService(userRepository);
    }

    @Nested
    @DisplayName("loadUser - OAuth2 Flow")
    class LoadUserTests {

        @Test
        @DisplayName("should create new user when Google email does not exist")
        void shouldCreateNewUserWhenEmailNotExists() throws Exception {
            // Given
            Map<String, Object> attributes = Map.of(
                    "email", "newuser@gmail.com",
                    "sub", "google-12345"
            );

            OAuth2User mockOAuth2User = new DefaultOAuth2User(
                    java.util.Collections.emptyList(),
                    attributes,
                    "sub"
            );

            // Mock the super class method
            var superField = org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.class.getDeclaredField("delegate");
            superField.setAccessible(true);

            DefaultOAuth2UserService mockSuperService = mock(DefaultOAuth2UserService.class);
            when(mockSuperService.loadUser(any(OAuth2UserRequest.class))).thenReturn(mockOAuth2User);

            // Inject mock into our service
            superField.set(googleOAuth2UserService, mockSuperService);

            when(userRepository.findByEmail("newuser@gmail.com")).thenReturn(Optional.empty());
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
                User user = invocation.getArgument(0);
                // Use reflection to set id (JPA will generate it anyway)
                try {
                    var idField = User.class.getDeclaredField("id");
                    idField.setAccessible(true);
                    idField.set(user, UUID.randomUUID());
                } catch (Exception e) {
                    // Ignore - id will be generated by DB
                }
                return user;
            });

            // When
            OAuth2User result = googleOAuth2UserService.loadUser(mock(OAuth2UserRequest.class));

            // Then
            assertThat(result).isInstanceOf(GoogleOAuth2UserPrincipal.class);

            ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
            verify(userRepository).save(userCaptor.capture());

            User savedUser = userCaptor.getValue();
            assertThat(savedUser.getEmail()).isEqualTo("newuser@gmail.com");
            assertThat(savedUser.getProvider()).isEqualTo(AuthProvider.GOOGLE);
            assertThat(savedUser.getRole()).isEqualTo(UserRole.USER);
        }

        @Test
        @DisplayName("should return existing user when Google email already exists")
        void shouldReturnExistingUserWhenEmailExists() throws Exception {
            // Given
            User existingUser = createTestUser("existing@gmail.com", AuthProvider.GOOGLE);

            Map<String, Object> attributes = Map.of(
                    "email", "existing@gmail.com",
                    "sub", "google-12345"
            );

            OAuth2User mockOAuth2User = new DefaultOAuth2User(
                    java.util.Collections.emptyList(),
                    attributes,
                    "sub"
            );

            // Mock the super class method
            var superField = org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.class.getDeclaredField("delegate");
            superField.setAccessible(true);

            DefaultOAuth2UserService mockSuperService = mock(DefaultOAuth2UserService.class);
            when(mockSuperService.loadUser(any(OAuth2UserRequest.class))).thenReturn(mockOAuth2User);

            // Inject mock into our service
            superField.set(googleOAuth2UserService, mockSuperService);

            when(userRepository.findByEmail("existing@gmail.com")).thenReturn(Optional.of(existingUser));

            // When
            OAuth2User result = googleOAuth2UserService.loadUser(mock(OAuth2UserRequest.class));

            // Then
            assertThat(result).isInstanceOf(GoogleOAuth2UserPrincipal.class);

            GoogleOAuth2UserPrincipal principal = (GoogleOAuth2UserPrincipal) result;
            assertThat(principal.getUser().getEmail()).isEqualTo("existing@gmail.com");

            verify(userRepository, never()).save(any(User.class));
        }

        @Test
        @DisplayName("should update provider to GOOGLE when LOCAL user links Google account")
        void shouldUpdateProviderToGoogleWhenLocalUserLinksAccount() throws Exception {
            // Given
            User localUser = createTestUser("local@gmail.com", AuthProvider.LOCAL);

            Map<String, Object> attributes = Map.of(
                    "email", "local@gmail.com",
                    "sub", "google-12345"
            );

            OAuth2User mockOAuth2User = new DefaultOAuth2User(
                    java.util.Collections.emptyList(),
                    attributes,
                    "sub"
            );

            // Mock the super class method
            var superField = org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.class.getDeclaredField("delegate");
            superField.setAccessible(true);

            DefaultOAuth2UserService mockSuperService = mock(DefaultOAuth2UserService.class);
            when(mockSuperService.loadUser(any(OAuth2UserRequest.class))).thenReturn(mockOAuth2User);

            // Inject mock into our service
            superField.set(googleOAuth2UserService, mockSuperService);

            when(userRepository.findByEmail("local@gmail.com")).thenReturn(Optional.of(localUser));
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

            // When
            OAuth2User result = googleOAuth2UserService.loadUser(mock(OAuth2UserRequest.class));

            // Then
            ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
            verify(userRepository).save(userCaptor.capture());

            User savedUser = userCaptor.getValue();
            assertThat(savedUser.getProvider()).isEqualTo(AuthProvider.GOOGLE);
        }

        @Test
        @DisplayName("should extract email and google ID from OAuth2 attributes")
        void shouldExtractEmailAndGoogleIdFromAttributes() throws Exception {
            // Given
            String expectedEmail = "testuser@gmail.com";
            String expectedGoogleId = "google-123456";

            Map<String, Object> attributes = Map.of(
                    "email", expectedEmail,
                    "sub", expectedGoogleId
            );

            OAuth2User mockOAuth2User = new DefaultOAuth2User(
                    java.util.Collections.emptyList(),
                    attributes,
                    "sub"
            );

            // Mock the super class method
            var superField = org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserService.class.getDeclaredField("delegate");
            superField.setAccessible(true);

            DefaultOAuth2UserService mockSuperService = mock(DefaultOAuth2UserService.class);
            when(mockSuperService.loadUser(any(OAuth2UserRequest.class))).thenReturn(mockOAuth2User);

            // Inject mock into our service
            superField.set(googleOAuth2UserService, mockSuperService);

            when(userRepository.findByEmail(expectedEmail)).thenReturn(Optional.empty());
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

            // When
            OAuth2User result = googleOAuth2UserService.loadUser(mock(OAuth2UserRequest.class));

            // Then
            assertThat(result).isInstanceOf(GoogleOAuth2UserPrincipal.class);
            GoogleOAuth2UserPrincipal principal = (GoogleOAuth2UserPrincipal) result;
            assertThat(principal.getUser().getEmail()).isEqualTo(expectedEmail);
        }
    }

    private User createTestUser(String email, AuthProvider provider) {
        User user = new User();
        try {
            var idField = User.class.getDeclaredField("id");
            idField.setAccessible(true);
            idField.set(user, UUID.randomUUID());
        } catch (Exception e) {
            // Ignore - test will handle
        }
        user.setEmail(email);
        user.setProvider(provider);
        user.setRole(UserRole.USER);
        return user;
    }
}
